basicapp/urls.py
from django.urls import path
from basicapp import views


app_name = 'matics_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('formpage/', views.form_view, name='form')
]

basicforms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('basicapp.urls')),
    path('admin/', admin.site.urls),
]

basicapp/models.py
from django.db import models

# Create your models here.

basicapp/forms.py
from django import forms
from django.core import validators

class FormName(forms.Form):



    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label="Enter your email again")
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False,
                                 widget=forms.HiddenInput,
                                 validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean = super().clean()

        email = all_clean.get('email')
        verif_email = all_clean.get('verify_email')

        if email != verif_email:
            raise forms.ValidationError("Email doesn't match")

basicapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import forms

# Create your views here.

def index(request):
    return render(request, "basicapp/index.html")

def form_view(request):
    form = forms.FormName;

    if request.method == 'POST':
        form = forms.FormName(request.POST)
        if form.is_valid():
            print('name: {}'.format(form.cleaned_data.get('name')))
            print('name: {}'.format(form.cleaned_data.get('email')))
            print('name: {}'.format(form.cleaned_data.get('text')))
    return render(request, "basicapp/form_page.html", {'form':form})

templates/basicapp/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basic Form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<h1>Fill out the form</h1>
<div class="container">
    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="Submit" class="btn btn-primary" value="submit">
    </form>

</div>
</body>
</html>

templates/basicapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to Mars</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Brand</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="{% url 'matics_app:form' %}">Register</a>



    </div>
  </div>
</nav>

<div class="container">
    <div class="jumbotron">
        <h1>Welcome to informatics Home page</h1>
    </div>
</div>

</body>
</html>